// Package main ...
package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/go-rod/rod/lib/utils"
)

var slash = filepath.FromSlash

func main() {

	build := utils.S(`// generated by running "go generate" on project root

package stealth

// JSVersion for stealth
const JSVersion = "v{{.ver}}"

// JS for stealth
const JS = {{.js}}
`,
		"ver", version(),
		"js", encode(fetchJS()),
	)

	utils.E(utils.OutputFile(slash("assets.go"), build))

	utils.ExecLine(true, "go install github.com/ysmood/golangci-lint@latest")
	utils.ExecLine(true, "golangci-lint")
}

func fetchJS() string {
	utils.ExecLine(true, "npx -ys -- extract-stealth-evasions@latest")

	code, err := utils.ReadString("stealth.min.js")
	utils.E(err)

	// since the npx already mentioned extract-stealth-evasions, we don't have to do it again.
	code = regexp.MustCompile(`\A/\*\![\s\S]+?\*/`).ReplaceAllString(code, "")

	return fmt.Sprintf(";(() => {\n%s\n})();", code)
}

func version() string {
	return strings.TrimSpace(utils.ExecLine(false, "npx -ys -- extract-stealth-evasions@latest --version"))
}

// not using encoding like base64 or gzip because of they will make git diff every large for small change
func encode(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "` + \"`\" + `") + "`"
}
