package main

import (
	"path/filepath"
	"strings"

	"github.com/ysmood/kit"
)

var slash = filepath.FromSlash

func main() {

	build := kit.S(`// generated by running "go generate" on project root

package bypass

// JS for bypass
const JS = {{.js}}
`,
		"js", fetchBypassJS(),
	)

	kit.E(kit.OutputFile(slash("assets.go"), build, nil))
}

func fetchBypassJS() string {
	code, err := kit.ReadString("puppeteer-dump/dist/stealth.js")
	kit.E(err)
	return encode(string(code))
}

// not using encoding like base64 or gzip because of they will make git diff every large for small change
func encode(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "` + \"`\" + `") + "`"
}
